const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTIONS_FAILURE'
    //UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS'
}

export default ShopActionTypes;